version: '3.8'

services:
  gail-chatbot:
    build: .
    container_name: gail-rag-chatbot
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=false
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
      - ./static:/app/static
      - ./templates:/app/templates
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: gail-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - gail-chatbot
    restart: unless-stopped

volumes:
  chroma_data:
  logs_data:

